name: Build and submit iOS
on:
  push:
    branches: ['main']
jobs:
  build:
    type: build
    params:
      platform: ios
      profile: production
  submit:
    needs: [build]
    type: submit
    params:
      platform: ios
      build_id: ${{ needs.build.outputs.build_id }}
