import { dayOfYear } from './dates';

/**
 * Daily prompts, rotated by day-of-year so the same date always shows
 * the same prompt (and next year invites a fresh comparison).
 */
const PROMPTS: string[] = [
  'What made today different from yesterday?',
  'What small thing brought you joy today?',
  'What did you learn today?',
  'Who made your day better, and how?',
  'What are you grateful for right now?',
  'What surprised you today?',
  'What would you tell your past self about today?',
  'What was the best moment of your day?',
  'What challenged you today?',
  'What did you notice today that you usually miss?',
  'How did you take care of yourself today?',
  'What made you laugh today?',
  'What are you looking forward to tomorrow?',
  'What would you do differently if today repeated?',
  'What did you make progress on today?',
  'Describe today in exactly six words.',
  'What conversation stuck with you today?',
  'What did you eat today that you enjoyed most?',
  'Where did you feel most at peace today?',
  'What took courage today, even a little?',
  'What did you let go of today?',
  'What song, image, or moment defined today?',
  'What kindness did you give or receive today?',
  'What is one thing you want to remember about today?',
  'What drained your energy today? What restored it?',
  'If today had a title, what would it be?',
  'What did you almost not do today, but did anyway?',
  'What felt like home today?',
  'What did you see today that was beautiful?',
  'What question are you sitting with tonight?',
  'What went better than expected today?',
  'What tiny victory deserves celebrating today?',
  'How was today’s weather — outside and inside you?',
  'What did you overhear or observe today worth keeping?',
  'What habit served you well today?',
  'What would your best friend say about your day?',
  'What moment today would make a good photograph?',
  'What did you resist today?',
  'What are you building toward right now?',
  'What did you do today that your future self will thank you for?',
  'What felt heavy today? Set it down here.',
  'What made you feel connected today?',
  'What idea grabbed you today?',
  'What was the quietest moment of your day?',
  'What are you proud of today, however small?',
  'What did you finish today?',
  'What did you start today?',
  'What rule did you break today — or wish you had?',
  'What did today teach you about yourself?',
  'Who did you think about today, unexpectedly?',
  'What color was today? Why?',
  'What are you curious about tonight?',
  'What did you say no to today?',
  'What did you say yes to today?',
  'What made today feel long — or short?',
  'What deserves more of your attention tomorrow?',
  'What was your first thought this morning?',
  'What smell or sound will you remember from today?',
  'What tiny detail made you smile today?',
  'What are you holding onto that you could write down and release?',
  'What went exactly as planned today?',
  'What beautifully failed to go as planned?',
  'What did you give today?',
  'What did you receive today?',
  'What place did you visit today — new or familiar?',
  'What would you like tomorrow-you to know?',
  'What made you feel strong today?',
  'What softened you today?',
  'What are you wrestling with right now?',
  'What felt effortless today?',
  'What did you choose today?',
  'What did you notice about someone you love today?',
  'What was worth the wait today?',
  'What did you fix today?',
  'What made time fly today?',
  'What tradition or ritual grounded you today?',
  'What compliment did you get — or deserve — today?',
  'What did you read, watch, or hear today worth noting?',
  'What risk did you take today?',
  'What comfort did you enjoy today?',
  'What boundary did you honor today?',
  'What surprised you about yourself today?',
  'What would you bottle from today if you could?',
  'What felt true today?',
  'What made today ordinary in the best way?',
  'What energy do you want to carry into tomorrow?',
  'What did you practice today?',
  'What moment today felt like a scene from a film?',
  'What are you becoming?',
  'What did today ask of you?',
  'What answer showed up today?',
];

export function promptForDay(dayKey: string): string {
  const idx = (dayOfYear(dayKey) - 1) % PROMPTS.length;
  return PROMPTS[idx];
}
